### ISSUE TITLE
Add option to not check for already installed packages

### ISSUE THREAD

**Issue by MarcDBehr** [rootstockmfg/rstk-sfdx-package-utils#10]
Hi John,

When I want to install all of the prereq packages in a **new** scratch org, I don't need to check for existing packages (which slows things down). Can you please add an option that allows the check for existing packages to be skipped and just for the install of all of the prereq's?

**Comment by ImJohnMDaniel** [comment]
Hey @MarcDBehr 

Can you give me an idea of how much of an impact you are seeing it take to conduct the pre-checks?

**Comment by MarcDBehr** [comment]
I have seen it take 1-2 minutes (other times it seems to be a few (<10) seconds), so it kinda varies.

**Comment by ImJohnMDaniel** [comment]
Ok.  That makes sense.  When it is taking 1-2 minutes, there is actually a timeout on the underlying `force:package:installed:list` command.  Once it times out, it performs a retry on the command and that seems to work.  Unfortunately, that creates the delay that you are seeing.  I mentioned this behavior to @sfdc-db-gmail over [here](https://github.com/forcedotcom/cli/issues/103) last summer.  The `force:package:installed:list` command has no timeout flag which complicates the issues some.

Anyway, I can see the value of adding a flag to "override the pre-installed check".  I should be able to get it in soon and will let you know.

**Comment by ImJohnMDaniel** [comment]
@MarcDBehr -- You are all set now.

Update to version [v0.1.12](https://www.npmjs.com/package/rstk-sfdx-package-utils/v/0.1.12).  The new flag is `--noprecheck`.

Let me know if you have questions.

Cheers!
