### ISSUE TITLE
Update README to show optional install method

### ISSUE THREAD

**Issue by MarcDBehr** [rootstockmfg/rstk-sfdx-package-utils#8]
If people are not using npm, you can also install via the command

`sfdx plugins:install rstk-sfdx-package-utils`

The README should show that option I think

**Comment by ImJohnMDaniel** [comment]
@MarcDBehr I agree that this would be nice to have.  Unfortunately, the README file is autogenerated by the OCLIF framework when it is published.  I have some control over how it assembles, but not full control.  At this point, I have not found a way to manage that aspect of the README file.  Eventually, I will get it straight, but for the moment, I am closing this as "wontfix"

**Comment by ImJohnMDaniel** [comment]
@MarcDBehr -- OK, I did figure this out and it was easier than I expected.  The change is in the repo now and released as v0.1.11.  Cheers!
